# Generated by Django 4.2.5 on 2023-09-27 12:30

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(choices=[('Sale Planning', 'Sale Planning'), ('SEO', 'SEO'), ('Web-Site Design', 'Web-Site Design')], default='SEO', max_length=20)),
                ('description', models.TextField(max_length=250)),
                ('picture', imagekit.models.fields.ProcessedImageField(upload_to='albums')),
            ],
        ),
    ]
